import path from 'path';
import axios, { AxiosBasicCredentials } from 'axios';
import { createTypesFiles, createIndexFiles } from './createTypesFiles';
import { OpenAPIV3 } from 'openapi-types';

export type ApiOptions = {
  container: string;
  host: string;
  swagger: string;
  auth?: AxiosBasicCredentials;
};

export type GeneratorOptions = {
  output: string;
  api: ApiOptions | ApiOptions[];
};

export async function generate({ output, api }: GeneratorOptions) {
  const ops = Array.isArray(api) ? api : [api];
  output = path.resolve(output);
  try {
    for (const op of ops) {
      const { swagger, host, container, auth } = op;
      if (typeof host === 'undefined') {
        throw new Error('host is required');
      }
      const uri = new URL(swagger, host).href;
      console.log(`GENERATOR: Fetch ${uri}`);

      const { data } = await axios.get<OpenAPIV3.Document>(uri, { auth });
      const header = `/** THIS FILE IS AUTOMATICALLY GENERATED FROM : ${uri} **/`;

      await createTypesFiles({
        host,
        data,
        container,
        output,
        header,
      });
    }

    const containers = ops.map((d) => d.container);
    await createIndexFiles({ output, containers });

    console.log(`GENERATOR: Generated successfully`);
  } catch (e) {
    const message = e instanceof Error ? e.message : 'unknown';
    console.log(`GENERATOR: Error (${message})`);
    process.exit(1);
  }
}
